name       : pulseview
version    : 0.4.0
release    : 4
source     :
    - http://sigrok.org/download/source/pulseview/pulseview-0.4.0.tar.gz : 78f8291045c6f65b4827b12e83c8e68cea2d5e7268b15a51aaca9726c8100eb9
license    : GPL-3.0-or-later
component  : office.scientific
summary    : A Qt-based visualizer for logic analyzers, oscilloscopes and multimeters
    supported by sigrok.
description: |
    The sigrok project aims at creating a portable, cross-platform, Free/Libre/Open-Source signal analysis software suite that supports various device types (such as logic analyzers, oscilloscopes, multimeters, and more). PulseView is a Qt-based LA/scope/MSO GUI for sigrok.
builddeps  :
    - pkgconfig(glibmm-2.4)
    - pkgconfig(gl)
    - pkgconfig(libsigrok)
    - pkgconfig(libsigrokdecode)
    - pkgconfig(Qt5Svg)
    - libboost-devel
rundeps    :
    - qt5-svg
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
