name       : pulseview
version    : 0.4.1
release    : 8
source     :
    - https://sigrok.org/download/source/pulseview/pulseview-0.4.1.tar.gz : 9ee7ce3dd1457c6a5f5e4e9c2469903a1f070ba077ea68535cc29ef1dfac6f2f
license    : GPL-3.0-or-later
component  : office.scientific
summary    : A Qt-based visualizer for logic analyzers, oscilloscopes and multimeters
    supported by sigrok.
description: |
    The sigrok project aims at creating a portable, cross-platform, Free/Libre/Open-Source signal analysis software suite that supports various device types (such as logic analyzers, oscilloscopes, multimeters, and more). PulseView is a Qt-based LA/scope/MSO GUI for sigrok.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(libsigrok)
    - pkgconfig(libsigrokdecode)
    - libboost-devel
rundeps    :
    - qt5-svg
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
